### ISSUE TITLE
unityのiOSビルド時、4つのエラーが発生してビルドが正常にできない

### ISSUE THREAD

**Issue by toshi2001** [SpriteStudio/SS6PlayerForUnity#86]
unityのiosビルド中に以下の4つのエラーメッセージが発生しました。

1つ目のエラー

`IL2CPP error for type 'System.Delegate' in assembly '/Applications/Unity/Hub/Editor/2020.3.22f1/jigsaw app/Temp/StagingArea/Data/Managed/mscorlib.dll'
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at Unity.IL2CPP.CodeWriters.ManagedSourceCodeWriter.Dispose() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CodeWriters/ManagedSourceCodeWriter.cs:line 51
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`1.FlushStream(GlobalWriteContext context, IGeneratedMethodCodeWriter stream, NPath filePath) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/SourceWriters/SourceWriterBase.cs:line 56
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`2.WorkerWriteItemsToFile(WorkItemData`2 data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling.Streams/FileLevelParallelStreamManager.cs:line 35
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 247`

2つ目のエラー

`IL2CPP error for type 'System.UriParser/UriQuirksVersion' in assembly '/Applications/Unity/Hub/Editor/2020.3.22f1/jigsaw app/Temp/StagingArea/Data/Managed/System.dll'
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Unity.IL2CPP.CppDeclarationsWriter.Write(SourceWritingContext context, StreamWriter writer, ICppDeclarations declarationsIn) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CppDeclarationsWriter.cs:line 142
   at Unity.IL2CPP.CodeWriters.ManagedSourceCodeWriter.Dispose() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CodeWriters/ManagedSourceCodeWriter.cs:line 44
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`1.FlushStream(GlobalWriteContext context, IGeneratedMethodCodeWriter stream, NPath filePath) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/SourceWriters/SourceWriterBase.cs:line 56
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`2.WorkerWriteItemsToFile(WorkItemData`2 data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling.Streams/FileLevelParallelStreamManager.cs:line 35
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 247`

3つ目のエラー　

`IL2CPP error for type 'UnityEngine.RaycastHit' in /Users/bokken/buildslave/unity/build/Modules/Physics/ScriptBindings/Dynamics.bindings.cs:61
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Unity.IL2CPP.CppDeclarationsWriter.Write(SourceWritingContext context, StreamWriter writer, ICppDeclarations declarationsIn) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CppDeclarationsWriter.cs:line 142
   at Unity.IL2CPP.CodeWriters.ManagedSourceCodeWriter.Dispose() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CodeWriters/ManagedSourceCodeWriter.cs:line 44
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`1.FlushStream(GlobalWriteContext context, IGeneratedMethodCodeWriter stream, NPath filePath) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/SourceWriters/SourceWriterBase.cs:line 56
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`2.WorkerWriteItemsToFile(WorkItemData`2 data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling.Streams/FileLevelParallelStreamManager.cs:line 35
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 247`

４つ目のエラー

`Exception: IL2CPP error for type 'System.Configuration.ConfigurationSection' in assembly '/Applications/Unity/Hub/Editor/2020.3.22f1/jigsaw app/Temp/StagingArea/Data/Managed/System.Configuration.dll'
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Unity.IL2CPP.CppDeclarationsWriter.Write(SourceWritingContext context, StreamWriter writer, ICppDeclarations declarationsIn) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CppDeclarationsWriter.cs:line 142
   at Unity.IL2CPP.CodeWriters.ManagedSourceCodeWriter.Dispose() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CodeWriters/ManagedSourceCodeWriter.cs:line 44
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`1.FlushStream(GlobalWriteContext context, IGenerateMethodCodeWriter stream, NPath filePath) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/SourceWriters/SourceWriterBase.cs:line 56
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`2.WorkerWriteItemsToFile(WorkItemData`2 data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling.Streams/FileLevelParallelStreamManager.cs:line 35
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 247
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:129)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:65)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:818)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:785)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:604)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:269)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:908)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs,UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:718)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessorSettings postProcessorSettings, UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:663)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:45)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:49)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:29)`

上記4つのエラーについて解決方法をご存知の方いたら助けてほしいです。

**Comment by wtsera** [comment]
OPTPiX ユーザーサポート 瀬良です。

ここは SS6Player For Unity の GitHub です。
ご指摘のエラーは、Unity のビルドに関する質問で、SS6Player For Unityに関するエラーでは無いことから、適切な回答は難しいです。

Unityの挙動に関するお問い合わせは、Unityのフォーラムをご利用いただくなどご検討ください。
よろしくお願いいたします。
